//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsInUsa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmitsReject
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public int UnivId { get; set; }
        public string UnivName { get; set; }
        public string Status { get; set; }
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int AdmitRow { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
