//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsInUsa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullProfile
    {
        public int Id { get; set; }
        public string UGCollege { get; set; }
        public string UGCourse { get; set; }
        public Nullable<decimal> UGScore { get; set; }
        public Nullable<int> UGBacklogs { get; set; }
        public Nullable<bool> AppearedGre { get; set; }
        public Nullable<decimal> GVerbal { get; set; }
        public Nullable<decimal> GQuant { get; set; }
        public Nullable<decimal> GAwa { get; set; }
        public Nullable<bool> Toefl { get; set; }
        public Nullable<bool> Ielts { get; set; }
        public Nullable<decimal> TIReading { get; set; }
        public Nullable<decimal> TIWriting { get; set; }
        public Nullable<decimal> TIListening { get; set; }
        public Nullable<decimal> TISpeaking { get; set; }
        public Nullable<decimal> WorkExperience { get; set; }
        public string Papers { get; set; }
        public string MSCourse { get; set; }
        public string Term { get; set; }
        public Nullable<decimal> Year { get; set; }
        public string DreamUniversity { get; set; }
        public Nullable<decimal> GDay { get; set; }
        public string GMonth { get; set; }
        public Nullable<decimal> GYear { get; set; }
        public Nullable<int> Sop { get; set; }
        public Nullable<int> Lor { get; set; }
        public Nullable<int> ExtraCurricular { get; set; }
        public Nullable<int> CommunityService { get; set; }
        public Nullable<decimal> personalScore { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
