//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsInUsa.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MsInUsEntities : DbContext
    {
        public MsInUsEntities()
            : base("name=MsInUsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<CourseWork> CourseWorks { get; set; }
        public DbSet<FullProfile> FullProfiles { get; set; }
        public DbSet<Universities_list> Universities_list { get; set; }
        public DbSet<University_Deadlines> University_Deadlines { get; set; }
        public DbSet<AdmitsReject> AdmitsRejects { get; set; }
    }
}
