//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsInUsa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class University_Deadlines
    {
        public int Univ_Id { get; set; }
        public string Course { get; set; }
        public string Term { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> CourseId { get; set; }
        public int RowId { get; set; }
    
        public virtual Universities_list Universities_list { get; set; }
    }
}
